# Generated by Django 3.2.6 on 2025-11-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id_alarma', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alarma',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='ClasificacionTutoria',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'clasificacion_tutoria',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('anio_ingreso', models.IntegerField(blank=True, null=True)),
                ('lugar_procedencia', models.CharField(blank=True, max_length=255, null=True)),
                ('grupo_familiar', models.TextField(blank=True, null=True)),
                ('beneficios_sociales', models.TextField(blank=True, null=True)),
                ('carrera', models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.PROTECT, to='sat.carrera')),
                ('estado_actual', models.ForeignKey(db_column='id_estado_actual', on_delete=django.db.models.deletion.PROTECT, to='sat.estado')),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoAlarma',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_alarma',
            },
        ),
        migrations.CreateModel(
            name='TipoDesercion',
            fields=[
                ('id_tipo_desercion', models.AutoField(primary_key=True, serialize=False)),
                ('causa', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_desercion',
            },
        ),
        migrations.CreateModel(
            name='TipoTutoria',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_tutoria',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('carrera', models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_de_carrera', to='sat.carrera')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='sat.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id_tutoria', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('tema_tutoria', models.TextField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=100)),
                ('clasificacion_tutoria', models.ForeignKey(db_column='id_clasificacion', on_delete=django.db.models.deletion.PROTECT, to='sat.clasificaciontutoria')),
                ('tipo_tutoria', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.PROTECT, to='sat.tipotutoria')),
                ('tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.PROTECT, to='sat.usuario')),
            ],
            options={
                'db_table': 'tutoria',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='sat.estado')),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='sat.estudiante')),
            ],
            options={
                'db_table': 'historial_estado',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_desercion',
            field=models.ForeignKey(blank=True, db_column='id_tipo_desercion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.tipodesercion'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tutor_asignado',
            field=models.ForeignKey(blank=True, db_column='id_tutor_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.usuario'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='encargado',
            field=models.ForeignKey(blank=True, db_column='id_encargado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carreras_a_cargo', to='sat.usuario'),
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('alarma', models.ForeignKey(blank=True, db_column='id_alarma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.alarma')),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.PROTECT, to='sat.estudiante')),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
        migrations.AddField(
            model_name='alarma',
            name='tipo_alarma',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.PROTECT, to='sat.tipoalarma'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('estado_asistencia', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.PROTECT, to='sat.estudiante')),
                ('tutoria', models.ForeignKey(db_column='id_tutoria', on_delete=django.db.models.deletion.PROTECT, to='sat.tutoria')),
            ],
            options={
                'db_table': 'asistencia',
                'unique_together': {('tutoria', 'estudiante')},
            },
        ),
    ]
