# Generated by Django 3.2.6 on 2025-11-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificaciontutoria',
            options={'verbose_name': 'Clasificación de tutoría', 'verbose_name_plural': 'Clasificaciones de tutoría'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='tipoalarma',
            options={'verbose_name': 'Tipo de alarma', 'verbose_name_plural': 'Tipos de alarma'},
        ),
        migrations.AlterModelOptions(
            name='tipodesercion',
            options={'verbose_name': 'Tipo de deserción', 'verbose_name_plural': 'Tipos de deserción'},
        ),
        migrations.AlterModelOptions(
            name='tipotutoria',
            options={'verbose_name': 'Tipo de tutoría', 'verbose_name_plural': 'Tipos de tutoría'},
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tutor_asignado',
            field=models.ForeignKey(blank=True, db_column='id_tutor_asignado', limit_choices_to={'rol__nombre': 'Tutor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.usuario'),
        ),
    ]
