# Generated by Django 3.2.6 on 2025-11-30 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0002_auto_20251120_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tutoria',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
