# Generated by Django 3.2.6 on 2026-01-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0003_auto_20251130_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='tutoria',
            field=models.ForeignKey(db_column='id_tutoria', on_delete=django.db.models.deletion.CASCADE, to='sat.tutoria'),
        ),
    ]
