# Generated by Django 3.2.6 on 2026-01-06 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0004_alter_asistencia_tutoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to='sat.usuario')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to='sat.usuario')),
                ('estudiante_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sat.estudiante')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
