# Generated by Django 3.2.6 on 2026-01-06 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0005_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='autor',
            field=models.ForeignKey(blank=True, db_column='id_autor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras_creadas', to='sat.usuario'),
        ),
    ]
