# Generated by Django 3.2.6 on 2026-02-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0006_bitacora_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='anio_academico',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='nivel_riesgo',
            field=models.IntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto')], default=1),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='origen_dato',
            field=models.CharField(blank=True, help_text='Origen del dato histórico', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nivel_riesgo_ia',
            field=models.IntegerField(default=0, help_text='0:Sano, 1:Bajo, 2:Medio, 3:Alto, 4:Crítico'),
        ),
    ]
