# Generated by Django 3.2.6 on 2026-02-09 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0007_auto_20260208_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nivel_riesgo_manual',
            field=models.IntegerField(blank=True, choices=[(0, 'Sano'), (1, 'Bajo'), (2, 'Medio'), (3, 'Alto')], help_text='Corrección manual del nivel de riesgo (prioridad sobre IA)', null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='riesgo_corregido_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última corrección manual', null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='riesgo_corregido_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la última corrección manual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_riesgo', to='sat.usuario'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nivel_riesgo_ia',
            field=models.IntegerField(default=0, help_text='0:Sano, 1:Bajo, 2:Medio, 3:Alto'),
        ),
    ]
