# Generated by Django 3.2.6 on 2026-03-21 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0008_auto_20260209_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='observacion_sobrescritura',
            field=models.TextField(blank=True, help_text='Justificación del Encargado al corregir la predicción de la IA', null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='riesgo_sobrescrito',
            field=models.BooleanField(default=False, help_text='Si True, el batch nocturno no sobreescribirá el nivel de riesgo manual'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nivel_riesgo_manual',
            field=models.IntegerField(blank=True, choices=[(0, 'Sin riesgo'), (1, 'Bajo'), (2, 'Medio'), (3, 'Alto')], help_text='Corrección manual del nivel de riesgo (prioridad sobre IA)', null=True),
        ),
        migrations.CreateModel(
            name='HistorialRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo_anterior', models.IntegerField(help_text='Nivel de riesgo antes del cambio')),
                ('riesgo_nuevo', models.IntegerField(help_text='Nivel de riesgo después del cambio')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el cambio')),
                ('origen_cambio', models.CharField(choices=[('ML', 'Automático ML'), ('HU', 'Manual Humano')], default='ML', help_text='Indica si el cambio fue por el batch de ML o por un humano', max_length=2)),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='historial_riesgo', to='sat.estudiante')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', help_text='Usuario que realizó el cambio manual (None si fue automático)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_riesgo_realizados', to='sat.usuario')),
            ],
            options={
                'verbose_name': 'Historial de Riesgo',
                'verbose_name_plural': 'Historial de Riesgos',
                'db_table': 'historial_riesgo',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
