# Generated by Django 3.2.6 on 2026-03-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0009_hitl_historial_riesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='riesgo_pendiente_validacion',
            field=models.BooleanField(default=False, help_text='Si True, la IA cambió el riesgo recientemente y el EC debe confirmar o corregir'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='riesgo_sobrescrito',
            field=models.BooleanField(default=False, help_text='Si True, el EC realizó la última corrección (etiqueta guardada para reentrenamiento)'),
        ),
    ]
