# Generated by Django 3.2.6 on 2026-05-30 06:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0010_add_riesgo_pendiente_validacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='nivel_riesgo',
            new_name='estado_atencion',
        ),
        migrations.CreateModel(
            name='ComentarioBitacora',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat.usuario')),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='sat.bitacora')),
            ],
            options={
                'db_table': 'comentario_bitacora',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
