# Generated by Django 3.2.6 on 2026-05-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat', '0011_auto_20260530_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='estado_atencion',
            field=models.IntegerField(choices=[(1, 'Resuelta / Cerrada'), (2, 'En Proceso / Siendo Atendida'), (3, 'Reportada / No Atendida')], default=3),
        ),
    ]
